services:
  - type: web
    name: zkp-db-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8080"
    healthCheckPath: /api/health
    plan: free
