services:
  - type: web
    name: zkp-db-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn provider_api:app --bind 0.0.0.0:${PORT}
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
